require:
 - rubocop-rails
 - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
